### ISSUE TITLE
premium plugins cause errors with "composer update"

### ISSUE THREAD

**Issue by michael-voit** [NANU-Wandel-Wege-entdecken/NANU-website#17]
when I downloaded the repository, I ran "composer update". I got an error, that the environment variable PLUGIN_KEY_ACF is not set. 

`[FFraenz\PrivateComposerInstaller\Exception\MissingEnvException]
  Can't resolve placeholder {%PLUGIN_KEY_ACF}. Environment variable 'PLUGIN_KEY_ACF' is not set.`

When I copied it from the example env-file as

`PLUGIN_KEY_ACF=pleasedontusethiskey`

and used "composer update" again, I got the next error:

```
[Composer\Downloader\TransportException]
  The "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k=pleasedontusethiskey&t=5.8.9" file could not be downloaded
  (HTTP/1.1 404 Not Found)
```

When I than put in my licencse key in the env-file - what other developers can't do as they don't have our license key - it doesn't change anything. It still shows the error after "composer update" with the k=pleasedontusethiskey in the download URL.

The same for WP Migrate DB Pro.

I had to delete both from the composer.json to be able to finish the "composer update".

So I think we have to streamline this process to give other developers a smoother start.

**Comment by ibes** [comment]
This are private date that are not supposed to go into a public repo. 

These information need to be sent to new developers in private communication. 

Beside doing exact that - sending a new developer this information - there would be the way to place this information in a private place where developers with access rights to eg. our github organisation etc. can get through a link that we provide.

**Comment by michael-voit** [comment]
@ibes 
Sorry, but I don't see that as "done"...

I don't think that every person who helps us one time or forks the repo to just play around with it, learn and perhaps later give back a few pull requests will get our license keys and passwords... but at the same time they should be able to work with it.

Let's think about it a little bit.

My thoughts:

- use as few premium plug-ins as possible
  - which do we have at the moment? (ACF Pro, WP Migrate DB Pro, MailPoet Premium, .... i think that's all)
  - do we really need them as premium?
  - is there a free alternative we could use?
  - is the free version of the premium plugin enough to work on local? (Yes for MailPoet, I think, as we can have just 5 subscribers in the dev-database for the website)
  - do we need all of this premium plugins in a local dev environment? (No for WP Migrate DB, for example)
- have a composer.json as it is now - and a composer.json.local or composer.json.dev without these pro plugins or their free variants and make clear in the dev documentation, that they have to delete composer.json and rename the other one into composer.json

What do you think? Could it be worth to think in that direction?

**Comment by ibes** [comment]
Make sure to recognize that you are mixing two issues. 

1) getting you set up - which is priority: high
2) finding ways to include other people in our work flow - which is far from priority: high. 

Please start a new issue for "2)" and copy over the brainstorm. 

I am very open to find solutions for "2)" in some weeks. 

Will not answer to issue 2) here.

**Comment by michael-voit** [comment]
@ibes one last comment (and later I will create a new issue): This IS the issue 2, as you named it. As I found my way to finish the composer update way before writing this issue.....

But no problem, we will look over it, in a new issue, in some weeks.

**Comment by ibes** [comment]
@michael-voit 
I am not confinced this was issue 2 from the start 😆

**Comment by michael-voit** [comment]
@ibes no matter, if you are convinced or not - if you would read the last two sentences of the issue, you would see: "i found my way to do it - let's help other developers to have an easier start".

But lets close that here - makes no sense to discuss such a quibbling.
