### ISSUE TITLE
SEO-Plugin with old version stopped "composer update"

### ISSUE THREAD

**Issue by michael-voit** [NANU-Wandel-Wege-entdecken/NANU-website#18]
As exact version constraints are used in the composer.json for this plugin and this specific version is so old that it is not available for download anymore, the process stopped here.

` The requested package wpackagist-plugin/seo-by-rank-math 1.0.42.3 exists as wpackagist-plugin/seo-by-rank-math[1.0.52, 1.0.52.1, 1.0.52.2, 1.0.52.3, 1.0.53, 1.0.53.1, 1.0.54, 1.0.54.1, 1.0.54.2, 1.0.54.3, 1.0.55, dev-trunk] but these are rejected by your constraint.`

**Comment by ibes** [comment]
... I had this fixed already just not yet pushed. 

In the future we will need to find a way to fix plugin versions to not just upgrade them per incident. 
This will be a topic for the next step.
