### ISSUE TITLE
outdated version of Composer

### ISSUE THREAD

**Issue by michael-voit** [NANU-Wandel-Wege-entdecken/NANU-website#21]
Just to not forget it:

While "composer update" I got

`Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2`

After upgrading to Composer 2 I got

`You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.`

So I rolled back to Composer 1 - but think we should have a look someday to be compatible with Composer 2.

**Comment by ibes** [comment]
Composer 2 is quite fresh. 

- [ ] upgrade ffraenz/private-composer-installer to v5.0.1 or newer https://github.com/ffraenz/private-composer-installer/releases/tag/v5.0.0

Please also check if you are using composer plugins locally - independent of the repo
