### ISSUE TITLE
Don't use Wordplate.... o_O

### ISSUE THREAD

**Issue by michael-voit** [NANU-Wandel-Wege-entdecken/NANU-website#22]
At the end of the installation process after composer update, I get

`Package wordplate/plate is abandoned, you should avoid using it. No replacement was suggested.`

Perhaps just funny, but I don't know, what exactly that means....

**Comment by ibes** [comment]
Plate - it is about plate, not about wordplate. 
Plate is a plugin that was provided by the developers of WordPlate to eg. decluter the admin interface and provide a couple of other simplifications to WordPress. 
https://www.producthunt.com/posts/administration-ui this was recommanded instead for a while - but seems like Vincent does not support it anymore.

**Comment by ibes** [comment]
- [ ] remove plate from dependencies
- [ ] remove https://github.com/NANU-Wandel-Wege-entdecken/NANU-website/blob/master/public/themes/nanu/inc/Plugins/Plate.php

**Comment by ibes** [comment]
Would be great to find an alternative or solve this inline. 
Plate was a good tool for get rid of unnecessary stuff.

**Comment by michael-voit** [comment]
@ibes Will you remember that or shall we create an issue to find a replacement?
